conditions:
  disable_vwap: 0
  trailing: 0
common:
  start: "9:30:00"
  stop: "14:45:00"
  check_secs: 60
  live: 1
  base: BANKNIFTY
  strategy: 2
BANKNIFTY:
  ulying: "NOT-IMPLEMENTED"
  exchange: NFO
  expiry: 03JUL24
  quantity: 15
  away_from_atm: 0
  band_width: 50
NIFTY:
  ulying: "NOT-IMPLEMENTED"
  exchange: NFO
  expiry: 13JUN24
  quantity: 50
  away_from_atm: 0
  band_width: 100
FINNIFTY:
  ulying: "NOT-IMPLEMENTED"
  exchange: NFO
  expiry: 11JUN24
  quantity: 40
  away_from_atm: 0
  band_width: 100
