conditions:
  disable_vwap: 0
common:
  start: "9:30:00"
  stop: "21:30:00"
  check_secs: 60
  live: 1
  base: FINNIFTY
BANKNIFTY:
  ulying: "NOT-IMPLEMENTED"
  exchange: NFO
  expiry: 15MAY24
  quantity: 15
  away_from_atm: 0
NIFTY:
  ulying: "NOT-IMPLEMENTED"
  exchange: NFO
  expiry: 18APR24
  quantity: 50
  away_from_atm: 0
FINNIFTY:
  ulying: "NOT-IMPLEMENTED"
  exchange: NFO
  expiry: 28MAY24
  quantity: 40
  away_from_atm: 0

